"""add dedup unique constraints

Revision ID: 86c7fcd66b17
Revises: fec8dd9c9bd8
Create Date: 2026-08-18 06:52:56.901760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c7fcd66b17'
down_revision: Union[str, None] = 'fec8dd9c9bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inventory_snapshot_identity', 'inventory_snapshots', ['business_id', 'product_id', 'channel_id', 'snapshot_date'])
    op.create_unique_constraint('uq_order_lines_order_channel_product', 'order_lines', ['order_id', 'channel_product_id'])
    op.create_unique_constraint('uq_orders_business_channel_external_id', 'orders', ['business_id', 'channel_id', 'external_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_business_channel_external_id', 'orders', type_='unique')
    op.drop_constraint('uq_order_lines_order_channel_product', 'order_lines', type_='unique')
    op.drop_constraint('uq_inventory_snapshot_identity', 'inventory_snapshots', type_='unique')
    # ### end Alembic commands ###
